### 中间件巩固-错误处理日志

捕获可能发生错误的地方

```javascript
app.get('/',(req,res,next)=>{
    try{
        // 必然发生错误;
        const data = JSON.parse('{name:}');
        res.json(data);
    }catch(e){
        next(e);
    }
})
```

设置中间件对错误进行日志记录,日志记录完后并对客户端进行500响应.

```javascript
// 统一的错误处理日志
app.use((err,req,res,next)=>{
    // console.log(err);
    const error_log = `
        =============================
        错误名: ${err.name}, \n
        错误信息:   ${err.message}, \n
        错误时间:   ${new Date()}, \n
        错误堆栈:   ${err.stack}, \n
        =============================
    `;
    fs.appendFile(path.join(__dirname,'error.log'),error_log,(err)=>{
        if(err) throw err;
        res.writeHead(500,{'Content-Type':'text/html;charset=utf-8'});
        res.end('500 服务器内部发生错误!');
    });
})
```

发生在预料内可能得错误也可以直接传递错误

```javascript
app.get('/b',(req,res,next)=>{
    fs.readFile(path.join(__dirname,'ccc.log'),(err,data)=>{
        if(err){
            next(err);
        }
    })
});
```
